import { jsPDF } from 'jspdf';
import { formatDate, shortId } from './screeningUtils';
import { OVERALL_CONFIG } from './screeningUtils';

// Builds a clean downloadable PDF screening report.
export function downloadScreeningReport(screening) {
  const result = screening.analysis_result || {};
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = margin;

  const accent = OVERALL_CONFIG[result.overall_status]?.ring || '#00F0FF';

  // Header band
  doc.setFillColor(7, 9, 14);
  doc.rect(0, 0, pageW, 70, 'F');
  doc.setTextColor(0, 240, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('AUTHENX', margin, 34);
  doc.setTextColor(180, 180, 190);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('AI-Assisted Screening Report', margin, 50);
  doc.text(formatDate(screening.created_date), pageW - margin, 34, { align: 'right' });
  doc.text('ID: ' + shortId(screening.id), pageW - margin, 50, { align: 'right' });

  y = 92;
  doc.setTextColor(30, 30, 35);

  const section = (title) => {
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(0, 120, 140);
    doc.text(title, margin, y);
    y += 6;
    doc.setDrawColor(220, 220, 225);
    doc.line(margin, y, pageW - margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 45);
  };

  const row = (label, value) => {
    doc.setTextColor(120, 120, 130);
    doc.text(label, margin, y);
    doc.setTextColor(30, 30, 35);
    const lines = doc.splitTextToSize(String(value || '—'), pageW - margin - 160);
    doc.text(lines, margin + 150, y);
    y += 14 * lines.length + 4;
  };

  section('Document Information');
  row('Document Type', result.document_type || screening.document_type);
  row('Overall Status', result.overall_status || screening.overall_status);
  row('Risk Score', (result.risk_score ?? screening.risk_score) + ' / 100');
  row('Mode', screening.demo_mode ? 'Demo Analysis Mode (simulated)' : 'Live AI Analysis');

  section('Extracted Fields');
  (result.extracted_fields || []).forEach((f) => {
    row(f.field_name, f.value + '  (conf: ' + Math.round(f.confidence * 100) + '%, ' + f.validation_status + ')');
  });

  section('Validation Results');
  (result.field_validation || []).forEach((v) => {
    row(v.check, v.status + ' — ' + v.detail);
  });

  section('Tampering Indicators');
  if ((result.tampering_indicators || []).length === 0) {
    row('Indicators', 'No significant tampering indicators detected.');
  } else {
    (result.tampering_indicators || []).forEach((f) => {
      row(f.finding + ' (' + f.severity + ')', f.explanation);
    });
  }

  section('Photo Comparison');
  const fc = result.face_comparison || {};
  row('Face Match Score', (fc.score ?? '—') + '%');
  row('Match Status', fc.status || '—');

  section('Risk Categories');
  (result.risk_categories || []).forEach((c) => row(c.name, c.score + ' / 100'));

  section('Notes');
  (result.explanations || []).forEach((e) => {
    const lines = doc.splitTextToSize('• ' + e, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += 14 * lines.length;
  });
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 160);
  const disclaimer = 'Generated by AUTHENX AI-Assisted Screening System. For hackathon demonstration using fictional/mock documents only. These are AI-assisted indicators for human review and do not constitute proof of fraud or official identity verification.';
  const dlines = doc.splitTextToSize(disclaimer, pageW - margin * 2);
  doc.text(dlines, margin, y);

  doc.save('AUTHENX-Screening-' + shortId(screening.id) + '.pdf');
}